apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netobserv-loki-gateway-tokenreviewer
  annotations:
    argocd.argoproj.io/sync-wave: "11"
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netobserv-loki-gateway-tokenreviewer
  annotations:
    argocd.argoproj.io/sync-wave: "11"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netobserv-loki-gateway-tokenreviewer
subjects:
  - kind: ServiceAccount
    name: loki-gateway
    namespace: netobserv
